-- Fresh installation only: structures + factory seeds, never production rows.

-- Statistics random secrets are generated by the installer, not this file.

SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `__PREFIX__bill`;

CREATE TABLE `__PREFIX__bill` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `owner` int(10) unsigned NOT NULL COMMENT '用户id',
  `amount` decimal(10,2) unsigned NOT NULL COMMENT '金额',
  `balance` decimal(14,2) unsigned NOT NULL COMMENT '余额',
  `type` tinyint(4) NOT NULL COMMENT '类型：0=支出，1=收入',
  `currency` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '货币：0=余额，1=硬币',
  `log` varchar(64) NOT NULL COMMENT '日志',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `owner` (`owner`) USING BTREE,
  KEY `type` (`type`) USING BTREE,
  CONSTRAINT `__PREFIX__bill_ibfk_1` FOREIGN KEY (`owner`) REFERENCES `__PREFIX__user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__business`;

CREATE TABLE `__PREFIX__business` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `user_id` int(10) unsigned NOT NULL COMMENT '用户id',
  `shop_name` varchar(32) DEFAULT NULL COMMENT '店铺名称',
  `title` varchar(32) DEFAULT NULL COMMENT '浏览器标题',
  `notice` text COMMENT '店铺公告',
  `service_qq` varchar(16) DEFAULT NULL COMMENT '客服QQ',
  `service_url` varchar(255) DEFAULT NULL COMMENT '网页客服链接',
  `subdomain` varchar(64) DEFAULT NULL COMMENT '子域名',
  `topdomain` varchar(64) DEFAULT NULL COMMENT '顶级域名',
  `master_display` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '主站显示：0=否，1=是',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `user_id` (`user_id`) USING BTREE,
  UNIQUE KEY `subdomain` (`subdomain`) USING BTREE,
  UNIQUE KEY `topdomain` (`topdomain`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__business_level`;

CREATE TABLE `__PREFIX__business_level` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` varchar(32) NOT NULL COMMENT '等级名称',
  `icon` varchar(255) DEFAULT NULL COMMENT '图标',
  `cost` decimal(4,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '商家自己的商品，抽成百分比',
  `accrual` decimal(4,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '主站商品，分给商家的收益百分比',
  `substation` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '分站：0=关闭，1=启用',
  `top_domain` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '顶级域名：0=关闭，1=启用',
  `price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '购买价格',
  `supplier` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '供货商权限：0=关闭，1=启用',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__card`;

CREATE TABLE `__PREFIX__card` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `owner` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属会员：0=系统，其他等于会员UID',
  `commodity_id` int(10) unsigned NOT NULL COMMENT '商品id',
  `draft` varchar(255) DEFAULT NULL COMMENT '预选信息',
  `secret` varchar(760) NOT NULL COMMENT '卡密信息',
  `create_time` datetime NOT NULL COMMENT '添加时间',
  `purchase_time` datetime DEFAULT NULL COMMENT '购买时间',
  `order_id` int(10) unsigned DEFAULT NULL COMMENT '订单id',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=未出售，1=已出售，2=已锁定',
  `note` varchar(64) DEFAULT NULL COMMENT '备注信息',
  `race` varchar(32) DEFAULT NULL COMMENT '商品种类',
  `sku` json DEFAULT NULL COMMENT 'SKU',
  `draft_premium` decimal(10,2) unsigned DEFAULT NULL COMMENT '预选加价',
  `cost` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '预选成本',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `owner` (`owner`) USING BTREE,
  KEY `commodity_id` (`commodity_id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE,
  KEY `secret` (`secret`) USING BTREE,
  KEY `status` (`status`) USING BTREE,
  KEY `note` (`note`) USING BTREE,
  KEY `race` (`race`) USING BTREE,
  CONSTRAINT `__PREFIX__card_ibfk_1` FOREIGN KEY (`commodity_id`) REFERENCES `__PREFIX__commodity` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__cash`;

CREATE TABLE `__PREFIX__cash` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `user_id` int(10) unsigned NOT NULL COMMENT '用户id',
  `amount` decimal(14,2) unsigned NOT NULL COMMENT '提现金额',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '类型：0=自动提现，1=手动提现',
  `card` tinyint(3) unsigned NOT NULL COMMENT '收款：0=支付宝，1=微信',
  `create_time` datetime NOT NULL COMMENT '提现时间',
  `arrive_time` datetime DEFAULT NULL COMMENT '到账时间',
  `cost` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '手续费',
  `status` tinyint(3) unsigned NOT NULL COMMENT '状态：0=处理中，1=成功，2=失败，3=冻结期',
  `message` varchar(64) DEFAULT NULL COMMENT '消息',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `type` (`type`) USING BTREE,
  KEY `message` (`message`) USING BTREE,
  CONSTRAINT `__PREFIX__cash_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `__PREFIX__user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__category`;

CREATE TABLE `__PREFIX__category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` varchar(255) CHARACTER SET utf8mb4 NOT NULL COMMENT '商品分类名称',
  `sort` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `owner` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属会员：0=系统，其他等于会员UID',
  `icon` varchar(255) DEFAULT NULL COMMENT '分类图标',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=停用，1=启用',
  `hide` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '隐藏：1=隐藏，0=不隐藏',
  `user_level_config` text COMMENT '会员配置',
  `pid` int(10) unsigned DEFAULT NULL COMMENT '上级ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `owner` (`owner`) USING BTREE,
  KEY `idx_category_pid` (`pid`) USING BTREE,
  KEY `sort` (`sort`) USING BTREE,
  CONSTRAINT `__PREFIX__ibfk_category_pid_in_id` FOREIGN KEY (`pid`) REFERENCES `__PREFIX__category` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__commodity`;

CREATE TABLE `__PREFIX__commodity` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `category_id` int(10) unsigned NOT NULL COMMENT '商品分类ID',
  `name` varchar(255) CHARACTER SET utf8mb4 NOT NULL COMMENT '商品名称',
  `description` text CHARACTER SET utf8mb4 COMMENT '商品说明',
  `cover` varchar(255) DEFAULT NULL COMMENT '商品封面图片',
  `factory_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '成本单价',
  `price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '商品单价(未登录)',
  `user_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '商品单价(会员价)',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=下架，1=上架',
  `owner` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属会员：0=系统，其他等于会员UID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `api_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'API对接：0=关闭，1=启用',
  `code` varchar(64) NOT NULL COMMENT '商品代码(API对接)',
  `delivery_way` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '发货方式：0=自动发货，1=手动发货/插件发货',
  `delivery_auto_mode` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '自动发卡模式：0=旧卡先发，1=随机发卡，2=新卡先发',
  `delivery_message` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '手动发货显示信息',
  `contact_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '联系方式：0=任意，1=手机，2=邮箱，3=QQ',
  `password_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '订单密码：0=关闭，1=启用',
  `sort` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
  `coupon` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '优惠卷：0=关闭，1=启用',
  `shared_id` int(10) unsigned DEFAULT NULL COMMENT '共享平台ID',
  `shared_code` varchar(64) DEFAULT NULL COMMENT '共享平台-商品代码',
  `shared_premium` float(10,2) unsigned DEFAULT '0.00' COMMENT '商品加价',
  `shared_stock` json DEFAULT NULL COMMENT '库存信息',
  `stock` int(11) DEFAULT NULL COMMENT '库存',
  `shared_premium_type` tinyint(3) unsigned DEFAULT '0' COMMENT '加价模式：0=固定金额，1=百分比，2=加价模板',
  `shared_premium_template` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '加价模板ID：0=未使用模板',
  `seckill_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品秒杀：0=关闭，1=开启',
  `seckill_start_time` datetime DEFAULT NULL COMMENT '秒杀开始时间',
  `seckill_end_time` datetime DEFAULT NULL COMMENT '秒杀结束时间',
  `draft_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '指定卡密购买：0=关闭，1=启用',
  `draft_premium` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '指定卡密购买时溢价',
  `inventory_hidden` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '隐藏库存：0=否，1=是',
  `leave_message` varchar(255) DEFAULT NULL COMMENT '发货留言',
  `recommend` tinyint(3) unsigned DEFAULT '0' COMMENT '推荐商品：0=否，1=是',
  `send_email` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '发送邮件：0=否，1=是',
  `only_user` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '限制登录购买：0=否，1=是',
  `purchase_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '限制购买数量：0=无限制',
  `widget` text CHARACTER SET utf8mb4 COMMENT '控件',
  `tags` varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '商品标签：JSON [{text,color}]',
  `level_price` text COMMENT '会员等级-定制价格',
  `level_disable` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '禁用会员等级折扣，0=关闭，1=启用',
  `minimum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最低购买数量，0=无限制',
  `maximum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最大购买数量，0=无限制',
  `shared_sync` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '同步平台价格：0=关，1=开',
  `config` text CHARACTER SET utf8mb4 COMMENT '配置文件',
  `hide` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '隐藏：1=隐藏，0=不隐藏',
  `inventory_sync` tinyint(4) NOT NULL DEFAULT '0' COMMENT '同步库存数量: 0=关，1=开',
  `shared_amount_sync` tinyint(3) unsigned DEFAULT '0' COMMENT '同步金额',
  `shared_config_sync` tinyint(3) unsigned DEFAULT '0' COMMENT '同步配置参数',
  `display_sales` int(10) unsigned DEFAULT NULL COMMENT '前台展示销量，空值使用真实销量',
  `display_heat_period` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '模拟热度增长周期：0=关闭，1=每小时，2=每天',
  `display_heat_step` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '每周期增加的模拟热度',
  `display_heat_started_at` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '模拟热度周期起点 Unix 秒',
  `channel_price` decimal(10,2) DEFAULT NULL,
  `channel_prices` mediumtext,
  `display_heat_random` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '展示销量随机增长：0=原固定模式，1=按小时受限随机',
  `display_heat_daily_cap` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '随机展示销量每日上限；按配置起点每24小时结算',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`) USING BTREE,
  KEY `owner` (`owner`) USING BTREE,
  KEY `status` (`status`) USING BTREE,
  KEY `sort` (`sort`) USING BTREE,
  KEY `category_id` (`category_id`) USING BTREE,
  KEY `shared_id` (`shared_id`) USING BTREE,
  KEY `seckill_status` (`seckill_status`) USING BTREE,
  KEY `api_status` (`api_status`) USING BTREE,
  KEY `recommend` (`recommend`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__config`;

CREATE TABLE `__PREFIX__config` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(128) NOT NULL COMMENT '配置键名称',
  `value` text CHARACTER SET utf8mb4 NOT NULL COMMENT '配置内容',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `key` (`key`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__coupon`;

CREATE TABLE `__PREFIX__coupon` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `code` varchar(32) NOT NULL COMMENT '优惠卷代码',
  `commodity_id` int(10) unsigned NOT NULL COMMENT '商品id',
  `owner` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属会员：0=系统，其他等于会员UID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `service_time` datetime DEFAULT NULL COMMENT '使用时间',
  `money` decimal(10,2) unsigned NOT NULL COMMENT '抵扣金额',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=未使用，1=已使用，2=锁定',
  `trade_no` char(22) DEFAULT NULL COMMENT '订单号',
  `note` varchar(32) DEFAULT NULL COMMENT '备注信息',
  `mode` tinyint(3) unsigned DEFAULT '0' COMMENT '抵扣模式',
  `category_id` int(10) unsigned DEFAULT '0' COMMENT '商品分类ID',
  `life` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '卡密使用寿命',
  `use_life` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '已使用次数',
  `race` varchar(32) DEFAULT NULL COMMENT '商品类别',
  `sku` json DEFAULT NULL COMMENT 'SKU',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`) USING BTREE,
  KEY `commodity_id` (`commodity_id`) USING BTREE,
  KEY `owner` (`owner`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `money` (`money`) USING BTREE,
  KEY `status` (`status`) USING BTREE,
  KEY `order_id` (`trade_no`) USING BTREE,
  KEY `note` (`note`) USING BTREE,
  KEY `race` (`race`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__manage`;

CREATE TABLE `__PREFIX__manage` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(64) NOT NULL COMMENT '邮箱',
  `password` varchar(64) NOT NULL COMMENT '密码',
  `security_password` varchar(64) DEFAULT NULL COMMENT '安全密码',
  `nickname` varchar(32) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '昵称',
  `salt` varchar(32) NOT NULL COMMENT '盐',
  `avatar` varchar(128) DEFAULT NULL COMMENT '头像',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=冻结，1=正常',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '类型：0=系统账号，1=普通账号(全天)，2=日间账号，3=夜间账号',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `login_time` datetime DEFAULT NULL COMMENT '登录时间',
  `last_login_time` datetime DEFAULT NULL COMMENT '上一次登录时间',
  `login_ip` varchar(128) DEFAULT NULL COMMENT '登录IP',
  `last_login_ip` varchar(128) DEFAULT NULL COMMENT '上一次登录IP',
  `note` varchar(255) DEFAULT NULL COMMENT '备注',
  `google_secret` varchar(64) DEFAULT NULL COMMENT '谷歌验证器密钥',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `username` (`email`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__manage_session`;

CREATE TABLE `__PREFIX__manage_session` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `manage_id` int(10) unsigned NOT NULL COMMENT '管理员id',
  `session_hash` char(64) NOT NULL COMMENT '会话标识SHA-256哈希',
  `device_type` varchar(16) NOT NULL COMMENT '设备类型',
  `device_name` varchar(96) NOT NULL COMMENT '设备名称',
  `user_agent` varchar(512) NOT NULL COMMENT '登录User-Agent',
  `login_ip` varchar(45) NOT NULL COMMENT '登录IP',
  `last_ip` varchar(45) NOT NULL COMMENT '最近IP',
  `created_time` datetime NOT NULL COMMENT '登录时间',
  `last_seen_time` datetime NOT NULL COMMENT '最近活跃时间',
  `expires_time` datetime NOT NULL COMMENT '过期时间',
  `revoked_time` datetime DEFAULT NULL COMMENT '撤销时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `session_hash` (`session_hash`) USING BTREE,
  KEY `manage_active` (`manage_id`,`revoked_time`,`expires_time`) USING BTREE,
  KEY `last_seen_time` (`last_seen_time`) USING BTREE,
  CONSTRAINT `__PREFIX__manage_session_ibfk_1` FOREIGN KEY (`manage_id`) REFERENCES `__PREFIX__manage` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__order`;

CREATE TABLE `__PREFIX__order` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `owner` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所属会员：0=游客，其他等于会员UID',
  `user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '商户ID：0=系统，其他等于会员ID',
  `trade_no` char(19) NOT NULL COMMENT '订单号',
  `amount` decimal(10,2) unsigned NOT NULL COMMENT '订单金额',
  `commodity_id` int(10) unsigned NOT NULL COMMENT '商品id',
  `card_id` int(10) unsigned DEFAULT NULL COMMENT '预选卡密id',
  `card_num` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '卡密数量',
  `pay_id` int(10) unsigned NOT NULL COMMENT '支付方式id',
  `create_time` datetime NOT NULL COMMENT '下单时间',
  `create_ip` varchar(64) NOT NULL COMMENT '下单IP',
  `create_device` tinyint(3) unsigned NOT NULL COMMENT '下单设备：0=电脑,1=安卓,2=IOS,3=IPAD',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '订单状态：0=未支付，1=已支付',
  `secret` longtext COMMENT '卡密信息',
  `password` varchar(32) DEFAULT NULL COMMENT '查询密码',
  `contact` varchar(32) DEFAULT NULL COMMENT '联系方式',
  `delivery_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '发货状态：0=未发货，1=已发货',
  `pay_url` varchar(1024) DEFAULT NULL,
  `coupon_id` int(10) unsigned DEFAULT NULL COMMENT '优惠卷id',
  `cost` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '手续费',
  `from` int(10) unsigned DEFAULT NULL COMMENT '推广人id',
  `premium` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '加价',
  `widget` text COMMENT '控件内容',
  `leave_message` text COMMENT '发货留言快照：下单时从商品复制，商品后续改动不影响历史订单',
  `rent` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '成本价',
  `race` varchar(32) DEFAULT NULL COMMENT '商品种类',
  `rebate` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '返利金额',
  `pay_cost` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '支付接口手续费',
  `gateway_amount` decimal(10,2) unsigned DEFAULT NULL COMMENT '提交给支付网关的CNY金额快照（站点货币×汇率，回调按此比对）',
  `sku` json DEFAULT NULL COMMENT 'SKU',
  `divide_amount` decimal(10,2) unsigned DEFAULT NULL COMMENT '推广者分成金额',
  `substation_user_id` int(10) unsigned DEFAULT NULL COMMENT '子站ID',
  `request_no` char(19) DEFAULT NULL COMMENT '请求id',
  `display_locale` varchar(8) NOT NULL DEFAULT 'zh-cn',
  `price_type` varchar(8) NOT NULL DEFAULT 'retail',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `trade_no` (`trade_no`) USING BTREE,
  UNIQUE KEY `request_no` (`request_no`) USING BTREE,
  KEY `commodity_id` (`commodity_id`) USING BTREE,
  KEY `pay_id` (`pay_id`) USING BTREE,
  KEY `contact` (`contact`) USING BTREE,
  KEY `create_ip` (`create_ip`) USING BTREE,
  KEY `owner` (`owner`) USING BTREE,
  KEY `from` (`from`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `card_id` (`card_id`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `delivery_status` (`delivery_status`) USING BTREE,
  KEY `substation_user_id` (`substation_user_id`) USING BTREE,
  KEY `coupon_id` (`coupon_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__order_option`;

CREATE TABLE `__PREFIX__order_option` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `option` text COMMENT '配置数据',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `order_id` (`order_id`) USING BTREE,
  CONSTRAINT `__PREFIX__order_option_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `__PREFIX__order` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__price_template`;

CREATE TABLE `__PREFIX__price_template` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` varchar(64) NOT NULL COMMENT '模板名称',
  `base` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '加价基准：0=成本价，1=当前售价',
  `guest_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '游客价加价方式：0=固定金额，1=百分比',
  `guest_value` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '游客价加价值',
  `user_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '会员价加价方式：0=固定金额，1=百分比',
  `user_value` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '会员价加价值',
  `level_config` text COMMENT '各会员等级加价规则：{等级id:{type,value}}',
  `rounding` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '价格取整：0=不取整，1=四舍五入到整元，2=向上取整到整元',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__pay`;

CREATE TABLE `__PREFIX__pay` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` varchar(16) NOT NULL COMMENT '支付名称',
  `icon` varchar(255) DEFAULT NULL COMMENT '图标',
  `code` varchar(32) NOT NULL COMMENT '支付代码',
  `commodity` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '前台状态：0=停用，1=启用',
  `recharge` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '充值状态：0=停用，1=启用',
  `create_time` datetime NOT NULL COMMENT '添加时间',
  `handle` varchar(64) NOT NULL COMMENT '支付平台',
  `pay_config_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '支付配置id(pay_config.id)：0=未选择配置',
  `sort` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
  `equipment` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '设备：0=通用，1=手机，2=电脑',
  `cost` decimal(10,3) unsigned DEFAULT '0.000' COMMENT '手续费',
  `cost_type` tinyint(3) unsigned DEFAULT '0' COMMENT '手续费模式：0=单笔固定，1=百分比',
  `archived` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '归档：0=正常，1=归档(仅保留供历史订单显示)',
  `buyer_method` varchar(16) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `commodity` (`commodity`) USING BTREE,
  KEY `recharge` (`recharge`) USING BTREE,
  KEY `sort` (`sort`) USING BTREE,
  KEY `equipment` (`equipment`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__pay_config`;

CREATE TABLE `__PREFIX__pay_config` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `handle` varchar(64) NOT NULL COMMENT '所属支付插件目录名(app/Pay/{handle})',
  `name` varchar(32) NOT NULL COMMENT '配置名称，站长自定义，如“主商户”“备用商户”',
  `config` mediumtext COMMENT '配置值：扁平JSON对象，键取自插件 Config/Submit 定义',
  `sort` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '最后修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `handle_name` (`handle`,`name`) USING BTREE,
  KEY `handle` (`handle`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__shared`;

CREATE TABLE `__PREFIX__shared` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '对接类型：0=内置，其他待扩展',
  `name` varchar(128) NOT NULL COMMENT '店铺名称',
  `domain` varchar(128) NOT NULL COMMENT '店铺地址',
  `app_id` varchar(32) NOT NULL COMMENT '商户ID',
  `app_key` varchar(64) NOT NULL COMMENT '密钥',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `balance` decimal(14,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '余额(缓存)',
  `currency` varchar(8) NOT NULL DEFAULT 'CNY' COMMENT '上游站点货币代码',
  `currency_rate` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '结算汇率：1 上游货币 = ? 本站货币；0 = 按站点汇率自动',
  `protocol` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '上游协议代次：0=未探明，1=3.1.2+，2=3.1.1及更老',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `domain` (`domain`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__user`;

CREATE TABLE `__PREFIX__user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `username` varchar(32) NOT NULL COMMENT '会员名',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(16) DEFAULT NULL COMMENT '手机',
  `qq` varchar(16) DEFAULT NULL COMMENT 'QQ号',
  `password` varchar(64) NOT NULL COMMENT '登录密码',
  `salt` varchar(32) NOT NULL COMMENT '盐',
  `app_key` varchar(32) NOT NULL COMMENT '对接密钥',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像',
  `balance` decimal(14,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '余额',
  `coin` decimal(14,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '硬币，可提现的币',
  `integral` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '积分',
  `create_time` datetime NOT NULL COMMENT '注册时间',
  `login_time` datetime DEFAULT NULL COMMENT '登录时间',
  `last_login_time` datetime DEFAULT NULL COMMENT '上一次登录时间',
  `login_ip` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '登录IP',
  `last_login_ip` varchar(128) CHARACTER SET utf8 DEFAULT NULL COMMENT '上一次登录IP',
  `pid` int(10) unsigned DEFAULT '0' COMMENT '上级ID',
  `recharge` decimal(14,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '累计充值',
  `total_coin` decimal(14,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '累计获得的硬币',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=封禁，1=正常',
  `business_level` int(10) unsigned DEFAULT NULL COMMENT '商户等级id',
  `nicename` varchar(10) DEFAULT NULL COMMENT '真实姓名',
  `alipay` varchar(64) DEFAULT NULL COMMENT '支付宝账号',
  `wechat` varchar(255) DEFAULT NULL COMMENT '微信收款二维码',
  `wallet_address` varchar(64) DEFAULT NULL COMMENT '钱包地址',
  `settlement` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '自动结算：0=支付宝，1=微信',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `username` (`username`) USING BTREE,
  UNIQUE KEY `email` (`email`) USING BTREE,
  UNIQUE KEY `phone` (`phone`) USING BTREE,
  KEY `pid` (`pid`) USING BTREE,
  KEY `business_level` (`business_level`) USING BTREE,
  KEY `coin` (`coin`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__user_category`;

CREATE TABLE `__PREFIX__user_category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `user_id` int(10) unsigned NOT NULL COMMENT '商家id',
  `category_id` int(10) unsigned NOT NULL COMMENT '分类id',
  `name` varchar(255) DEFAULT NULL COMMENT '自定义分类名称',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=屏蔽，1=显示',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `user_id` (`user_id`,`category_id`) USING BTREE,
  KEY `status` (`status`) USING BTREE,
  KEY `__PREFIX__user_category_ibfk_2` (`category_id`) USING BTREE,
  KEY `user_id_2` (`user_id`) USING BTREE,
  CONSTRAINT `__PREFIX__user_category_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `__PREFIX__user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `__PREFIX__user_category_ibfk_2` FOREIGN KEY (`category_id`) REFERENCES `__PREFIX__category` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__user_commodity`;

CREATE TABLE `__PREFIX__user_commodity` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `user_id` int(10) unsigned NOT NULL COMMENT '商家id',
  `commodity_id` int(10) unsigned NOT NULL COMMENT '商品id',
  `premium` float(10,2) unsigned DEFAULT '0.00' COMMENT '商品加价',
  `rounding` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '价格取整：0=不取整，1=四舍五入到整元，2=向上取整到整元',
  `name` varchar(255) DEFAULT NULL COMMENT '自定义名称',
  `description` text COMMENT '自定义商品介绍，NULL/空=沿用主站',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=隐藏，1=显示',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `user_id` (`user_id`,`commodity_id`) USING BTREE,
  KEY `commodity_id` (`commodity_id`) USING BTREE,
  KEY `user_id_2` (`user_id`) USING BTREE,
  KEY `status` (`status`) USING BTREE,
  CONSTRAINT `__PREFIX__user_commodity_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `__PREFIX__user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `__PREFIX__user_commodity_ibfk_2` FOREIGN KEY (`commodity_id`) REFERENCES `__PREFIX__commodity` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__user_group`;

CREATE TABLE `__PREFIX__user_group` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` varchar(32) NOT NULL COMMENT '等级名称',
  `icon` varchar(128) DEFAULT NULL COMMENT '等级图标',
  `discount_config` text COMMENT '折扣配置',
  `cost` decimal(4,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '抽成比例',
  `recharge` decimal(14,2) unsigned NOT NULL COMMENT '累计充值(达到该等级)',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `recharge` (`recharge`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__user_recharge`;

CREATE TABLE `__PREFIX__user_recharge` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `trade_no` char(22) NOT NULL COMMENT '订单号',
  `user_id` int(10) unsigned NOT NULL COMMENT '用户id',
  `amount` decimal(10,2) unsigned NOT NULL COMMENT '充值金额',
  `pay_cost` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '支付接口手续费',
  `gateway_amount` decimal(10,2) unsigned DEFAULT NULL COMMENT '提交给支付网关的CNY金额快照（站点货币×汇率，回调按此比对）',
  `pay_id` int(10) unsigned NOT NULL COMMENT '支付id',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=未支付，1=已支付',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `create_ip` varchar(64) NOT NULL COMMENT '下单IP',
  `pay_url` varchar(255) DEFAULT NULL COMMENT '支付地址',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `option` text COMMENT '配置参数',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `trade_no` (`trade_no`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `pay_id` (`pay_id`) USING BTREE,
  KEY `status` (`status`) USING BTREE,
  CONSTRAINT `__PREFIX__user_recharge_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `__PREFIX__user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__manage_log`;

CREATE TABLE `__PREFIX__manage_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `email` varchar(64) NOT NULL COMMENT '管理员邮箱',
  `nickname` varchar(32) NOT NULL COMMENT '管理员呢称',
  `content` varchar(128) NOT NULL COMMENT '日志内容',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `create_ip` varchar(64) NOT NULL COMMENT 'IP地址',
  `ua` varchar(255) DEFAULT NULL COMMENT '浏览器UA',
  `risk` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '风险：0=正常，1=异常',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `create_ip` (`create_ip`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `risk` (`risk`) USING BTREE,
  KEY `email` (`email`) USING BTREE,
  KEY `nickname` (`nickname`) USING BTREE,
  KEY `content` (`content`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__commodity_group`;

CREATE TABLE `__PREFIX__commodity_group` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` varchar(32) NOT NULL COMMENT '组名称',
  `commodity_list` json DEFAULT NULL COMMENT '商品列表',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `__PREFIX__upload`;

CREATE TABLE `__PREFIX__upload` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned DEFAULT NULL COMMENT 'null=后台',
  `hash` varchar(32) NOT NULL COMMENT '文件MD5',
  `type` varchar(8) NOT NULL COMMENT '文件类型',
  `path` varchar(255) NOT NULL COMMENT '文件路径',
  `create_time` datetime NOT NULL COMMENT '上传时间',
  `note` varchar(32) DEFAULT NULL COMMENT '文件备注',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `hash` (`hash`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `type` (`type`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `note` (`note`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `__PREFIX__ticket`;

CREATE TABLE `__PREFIX__ticket` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `ticket_no` char(22) NOT NULL COMMENT '工单编号',
  `user_id` int(10) unsigned NOT NULL COMMENT '创建会员id',
  `type` tinyint(3) unsigned NOT NULL COMMENT '类型：0=售前咨询，1=售后支持',
  `priority` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '优先级：0=低，1=中，2=高',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0=待客服，1=待用户，2=已解决，3=已关闭',
  `title` varchar(100) NOT NULL COMMENT '标题',
  `commodity_id` int(10) unsigned DEFAULT NULL COMMENT '关联商品id',
  `commodity_name` varchar(255) DEFAULT NULL COMMENT '商品名称快照',
  `order_id` int(10) unsigned DEFAULT NULL COMMENT '关联订单id',
  `order_trade_no` char(19) DEFAULT NULL COMMENT '订单号快照',
  `order_source` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '订单来源：0=无，1=会员，2=游客',
  `proof_upload_id` int(10) unsigned DEFAULT NULL COMMENT '购买凭证上传记录id',
  `proof_path` varchar(255) DEFAULT NULL COMMENT '购买凭证路径快照',
  `last_message_id` bigint(20) unsigned DEFAULT NULL COMMENT '最后消息id',
  `last_sender_type` tinyint(3) unsigned DEFAULT NULL COMMENT '最后发言方：0=用户，1=管理员，2=系统',
  `last_message_excerpt` varchar(255) DEFAULT NULL COMMENT '最后消息摘要',
  `last_message_time` datetime DEFAULT NULL COMMENT '最后消息时间',
  `user_unread` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '用户未读数',
  `manage_unread` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '后台未读数',
  `closed_by` int(10) unsigned DEFAULT NULL COMMENT '结束工单的管理员id',
  `closed_time` datetime DEFAULT NULL COMMENT '结束时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `ticket_no` (`ticket_no`) USING BTREE,
  KEY `user_status_message` (`user_id`,`status`,`last_message_time`) USING BTREE,
  KEY `status_priority_message` (`status`,`priority`,`last_message_time`) USING BTREE,
  KEY `commodity_id` (`commodity_id`) USING BTREE,
  KEY `order_id` (`order_id`) USING BTREE,
  KEY `proof_upload_id` (`proof_upload_id`) USING BTREE,
  KEY `closed_by` (`closed_by`) USING BTREE,
  CONSTRAINT `__PREFIX__ticket_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `__PREFIX__user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `__PREFIX__ticket_ibfk_2` FOREIGN KEY (`commodity_id`) REFERENCES `__PREFIX__commodity` (`id`) ON DELETE SET NULL,
  CONSTRAINT `__PREFIX__ticket_ibfk_3` FOREIGN KEY (`order_id`) REFERENCES `__PREFIX__order` (`id`) ON DELETE SET NULL,
  CONSTRAINT `__PREFIX__ticket_ibfk_4` FOREIGN KEY (`proof_upload_id`) REFERENCES `__PREFIX__upload` (`id`) ON DELETE SET NULL,
  CONSTRAINT `__PREFIX__ticket_ibfk_5` FOREIGN KEY (`closed_by`) REFERENCES `__PREFIX__manage` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__ticket_message`;

CREATE TABLE `__PREFIX__ticket_message` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `ticket_id` int(10) unsigned NOT NULL COMMENT '工单id',
  `sender_type` tinyint(3) unsigned NOT NULL COMMENT '发送方：0=用户，1=管理员，2=系统',
  `sender_id` int(10) unsigned DEFAULT NULL COMMENT '发送方id',
  `sender_name` varchar(32) NOT NULL COMMENT '发送方名称快照',
  `kind` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '消息类型：0=正文，1=解决回复，2=关闭事件',
  `content` longtext COMMENT '消息内容',
  `create_ip` varchar(64) NOT NULL COMMENT '发送IP',
  `create_time` datetime NOT NULL COMMENT '发送时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `ticket_message_id` (`ticket_id`,`id`) USING BTREE,
  KEY `sender` (`sender_type`,`sender_id`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  CONSTRAINT `__PREFIX__ticket_message_ibfk_1` FOREIGN KEY (`ticket_id`) REFERENCES `__PREFIX__ticket` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__system_message`;

CREATE TABLE `__PREFIX__system_message` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `audience_type` tinyint(3) unsigned NOT NULL COMMENT '接收范围：0=全体用户，1=会员等级，2=指定用户',
  `audience_id` int(10) unsigned DEFAULT NULL COMMENT '会员等级id或指定用户id',
  `audience_name` varchar(64) NOT NULL COMMENT '接收范围名称快照',
  `title` varchar(100) NOT NULL COMMENT '消息标题',
  `content` longtext NOT NULL COMMENT '净化后的消息正文',
  `summary` varchar(255) NOT NULL COMMENT '消息摘要',
  `jump_url` varchar(2048) DEFAULT NULL COMMENT '点击跳转地址',
  `recipient_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发送时接收人数',
  `created_by` int(10) unsigned DEFAULT NULL COMMENT '创建管理员id',
  `updated_by` int(10) unsigned DEFAULT NULL COMMENT '最后编辑管理员id',
  `manage_name` varchar(64) NOT NULL COMMENT '创建管理员名称快照',
  `update_manage_name` varchar(64) NOT NULL COMMENT '最后编辑管理员名称快照',
  `create_time` datetime NOT NULL COMMENT '发送时间',
  `update_time` datetime NOT NULL COMMENT '最后编辑时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `audience` (`audience_type`,`audience_id`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `created_by` (`created_by`) USING BTREE,
  KEY `updated_by` (`updated_by`) USING BTREE,
  CONSTRAINT `__PREFIX__system_message_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `__PREFIX__manage` (`id`) ON DELETE SET NULL,
  CONSTRAINT `__PREFIX__system_message_ibfk_2` FOREIGN KEY (`updated_by`) REFERENCES `__PREFIX__manage` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__user_message`;

CREATE TABLE `__PREFIX__user_message` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `message_id` int(10) unsigned NOT NULL COMMENT '系统消息id',
  `user_id` int(10) unsigned NOT NULL COMMENT '接收用户id',
  `read_time` datetime DEFAULT NULL COMMENT '首次阅读时间',
  `create_time` datetime NOT NULL COMMENT '接收时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `message_user` (`message_id`,`user_id`) USING BTREE,
  KEY `user_message` (`user_id`,`id`) USING BTREE,
  KEY `user_read_message` (`user_id`,`read_time`,`id`) USING BTREE,
  CONSTRAINT `__PREFIX__user_message_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `__PREFIX__system_message` (`id`) ON DELETE CASCADE,
  CONSTRAINT `__PREFIX__user_message_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `__PREFIX__user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__lang`;

CREATE TABLE `__PREFIX__lang` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `hash` char(32) NOT NULL COMMENT 'md5(source)',
  `source` text NOT NULL COMMENT '中文原文',
  `lang` varchar(8) NOT NULL COMMENT '目标语言:zh-tw/en/ja',
  `text` text COMMENT '译文,NULL=待翻译',
  `scene` varchar(32) NOT NULL DEFAULT '' COMMENT '来源场景:tpl/js/api/dyn/ext:{扩展名}',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '0=待翻译 1=机器翻译 2=人工确认',
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_hash_lang` (`hash`,`lang`) USING BTREE,
  KEY `idx_lang_status` (`lang`,`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `__PREFIX__content_translation`;

CREATE TABLE `__PREFIX__content_translation` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entity_type` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entity_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locale` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `field` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `text` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_revision` int(10) unsigned NOT NULL DEFAULT '1',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `update_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `content_translation_identity` (`entity_type`,`entity_id`,`locale`,`field`),
  KEY `content_translation_public` (`entity_type`,`locale`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `__PREFIX__store_content`;

CREATE TABLE `__PREFIX__store_content` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(96) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,
  `summary` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `url` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `image` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `payload` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `sort` int(11) NOT NULL DEFAULT '0',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `source_revision` int(10) unsigned NOT NULL DEFAULT '1',
  `revision` int(10) unsigned NOT NULL DEFAULT '1',
  `create_time` datetime NOT NULL,
  `update_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `store_content_type_slug` (`type`,`slug`),
  KEY `store_content_public` (`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `__PREFIX__usdt_buyer_lock`;

CREATE TABLE `__PREFIX__usdt_buyer_lock` (
  `buyer_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_seen` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`buyer_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `__PREFIX__usdt_payment`;

CREATE TABLE `__PREFIX__usdt_payment` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trade_no` varchar(18) COLLATE utf8mb4_unicode_ci NOT NULL,
  `pay_id` int(10) unsigned NOT NULL,
  `buyer_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cny_amount` decimal(14,2) NOT NULL,
  `receive_address` varchar(34) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `amount_units` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `active_match_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `config_snapshot` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `poll_token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `expires_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `settlement_expires_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `reservation_until` bigint(20) unsigned NOT NULL DEFAULT '0',
  `last_check_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `checking_until` bigint(20) unsigned NOT NULL DEFAULT '0',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `txid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `from_address` varchar(34) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paid_at` bigint(20) unsigned DEFAULT NULL,
  `block_time` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `usdt_payment_trade_no_unique` (`trade_no`),
  UNIQUE KEY `usdt_payment_active_match_key_unique` (`active_match_key`),
  UNIQUE KEY `usdt_payment_txid_unique` (`txid`),
  KEY `usdt_payment_status_settlement_expires_at_index` (`status`,`settlement_expires_at`),
  KEY `usdt_payment_reservation_until_index` (`reservation_until`),
  KEY `usdt_payment_buyer_key_index` (`buyer_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `__PREFIX__visit_sources_minute`;

CREATE TABLE `__PREFIX__visit_sources_minute` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `stat_date` date NOT NULL,
  `stat_hour` tinyint(3) unsigned NOT NULL,
  `stat_minute` tinyint(3) unsigned NOT NULL,
  `visitor_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_key` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_domain` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `pageviews` int(10) unsigned NOT NULL DEFAULT '1',
  `first_seen` datetime NOT NULL,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `visit_source_minute` (`stat_date`,`stat_hour`,`stat_minute`,`visitor_key`,`source_key`,`source_domain`),
  KEY `visit_source_date_visitor` (`stat_date`,`visitor_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `__PREFIX__visit_statistics_meta`;

CREATE TABLE `__PREFIX__visit_statistics_meta` (
  `meta_key` varchar(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `meta_value` varchar(255) NOT NULL,
  PRIMARY KEY (`meta_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `__PREFIX__visit_statistics_minute`;

CREATE TABLE `__PREFIX__visit_statistics_minute` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `stat_date` date NOT NULL,
  `stat_hour` tinyint(3) unsigned NOT NULL,
  `stat_minute` tinyint(3) unsigned NOT NULL,
  `visitor_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `device` varchar(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `country` char(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `pageviews` int(10) unsigned NOT NULL DEFAULT '1',
  `first_seen` datetime NOT NULL,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `visit_minute_visitor` (`stat_date`,`stat_hour`,`stat_minute`,`visitor_key`,`device`,`country`),
  KEY `visit_date_visitor` (`stat_date`,`visitor_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `__PREFIX__business_level` (`id`, `name`, `icon`, `cost`, `accrual`, `substation`, `top_domain`, `price`, `supplier`) VALUES (1, '体验版', '/assets/static/images/business/v1.png', 0.30, 0.10, 1, 0, 188.00, 1);

INSERT INTO `__PREFIX__business_level` (`id`, `name`, `icon`, `cost`, `accrual`, `substation`, `top_domain`, `price`, `supplier`) VALUES (3, '普通版', '/assets/static/images/business/v2.png', 0.25, 0.15, 1, 0, 288.00, 1);

INSERT INTO `__PREFIX__business_level` (`id`, `name`, `icon`, `cost`, `accrual`, `substation`, `top_domain`, `price`, `supplier`) VALUES (4, '专业版', '/assets/static/images/business/v3.png', 0.20, 0.20, 1, 1, 388.00, 1);

INSERT INTO `__PREFIX__category` (`id`, `name`, `sort`, `create_time`, `owner`, `icon`, `status`, `hide`, `user_level_config`, `pid`) VALUES (1, 'DEMO', 1, '2021-11-26 17:59:45', 0, '/favicon.ico', 1, 0, NULL , NULL);

INSERT INTO `__PREFIX__commodity` (`id`, `category_id`, `name`, `description`, `cover`, `factory_price`, `price`, `user_price`, `status`, `owner`, `create_time`, `api_status`, `code`, `delivery_way`, `sort`, `coupon`, `stock`)
VALUES (1, 1, 'DEMO', '<p>该商品是演示商品</p>', '/favicon.ico', 0.00, 1.00, 0.90, 1, 0, '2021-11-26 18:01:30', 1, '8AE80574F3CA98BE', 1, 1, 1, 999999);

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (1, 'shop_name', '异次元店铺');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (2, 'title', '异次元店铺 - 最适合你的个人店铺系统！');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (3, 'description', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (4, 'keywords', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (14, 'user_theme', 'LocalStar');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (5, 'registered_state', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (6, 'registered_type', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (7, 'registered_verification', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (8, 'registered_phone_verification', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (9, 'registered_email_verification', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (10, 'sms_config', '{\"accessKeyId\":\"\",\"accessKeySecret\":\"\",\"signName\":\"\",\"templateCode\":\"\"}');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (11, 'email_config', '{\"smtp\":\"\",\"port\":\"\",\"username\":\"\",\"password\":\"\"}');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (12, 'login_verification', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (13, 'forget_type', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (15, 'notice', '<p><b><font color=\"#f9963b\">本程序为开源程序，使用者造成的一切法律后果与作者无关。</font></b></p>');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (16, 'trade_verification', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (17, 'recharge_welfare', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (18, 'recharge_welfare_config', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (19, 'promote_rebate_v1', '0.1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (20, 'promote_rebate_v2', '0.2');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (21, 'promote_rebate_v3', '0.3');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (22, 'substation_display', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (24, 'domain', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (25, 'service_qq', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (26, 'service_url', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (27, 'cash_type_alipay', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (28, 'cash_type_wechat', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (29, 'cash_cost', '5');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (30, 'cash_min', '100');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (31, 'cname', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (32, 'background_url', '/assets/admin/images/login/bg.jpg');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (33, 'default_category', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (34, 'substation_display_list', '[]');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (35, 'closed', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (36, 'closed_message', '我们正在升级，请耐心等待完成。');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (37, 'recharge_min', '10');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (38, 'recharge_max', '1000');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (39, 'user_mobile_theme', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (40, 'commodity_recommend', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (41, 'commodity_name', '推荐');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (42, 'background_mobile_url', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (43, 'username_len', '6');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (44, 'cash_type_balance', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (45, 'callback_domain', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (46, 'session_expire', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (47, 'cash_type_usdt', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (48, 'user_center_theme', 'MountFuji');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (49, 'user_center_mobile_theme', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (50, 'callback_ip_whitelist', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (51, 'callback_ip_whitelist_rules', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (52, 'force_login', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (53, 'admin_login_verification', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (54, 'request_log', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (55, 'admin_entrance', '');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (56, 'lang_version', '0');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (57, 'currency_code', 'CNY');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (58, 'currency_symbol', '¥');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (59, 'currency_rate', '1');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (60, 'currency_decimals', '2');

INSERT INTO `__PREFIX__config` (`id`, `key`, `value`) VALUES (61, 'csp_mode', 'enforce');

INSERT INTO `__PREFIX__manage` (`id`, `email`, `password`, `security_password`, `nickname`, `salt`, `avatar`, `status`, `type`, `create_time`, `login_time`, `last_login_time`, `login_ip`, `last_login_ip`, `note`, `google_secret`) VALUES (1, '__MANAGE_EMAIL__', '__MANAGE_PASSWORD__', NULL, '__MANAGE_NICKNAME__', '__MANAGE_SALT__', '/favicon.ico', 1, 0, '1997-01-01 00:00:00', NULL , NULL, NULL, NULL, NULL, NULL);

INSERT INTO `__PREFIX__pay` (`id`, `name`, `icon`, `code`, `commodity`, `recharge`, `create_time`, `handle`, `pay_config_id`, `sort`, `equipment`, `cost`, `cost_type`, `archived`) VALUES (1, '余额', '/assets/static/images/wallet.png', '#system', 1, 0, '1997-01-01 00:00:00', '#system', 0, 999, 0, 0.000, 0, 0);

INSERT INTO `__PREFIX__pay` (`id`, `name`, `icon`, `code`, `commodity`, `recharge`, `create_time`, `handle`, `pay_config_id`, `sort`, `equipment`, `cost`, `cost_type`, `archived`) VALUES (2, '支付宝', '/assets/user/images/cash/alipay.png', 'alipay', 1, 1, '1997-01-01 00:00:00', 'Epay', 0, 1, 0, 0.000, 0, 0);

INSERT INTO `__PREFIX__user_group` (`id`, `name`, `icon`, `discount_config`, `cost`, `recharge`) VALUES (1, '一贫如洗', '/assets/static/images/group/ic_user level_1.png', null, 0.30, 0.00);

INSERT INTO `__PREFIX__user_group` (`id`, `name`, `icon`, `discount_config`, `cost`, `recharge`) VALUES (2, '小康之家', '/assets/static/images/group/ic_user level_2.png', null, 0.25, 50.00);

INSERT INTO `__PREFIX__user_group` (`id`, `name`, `icon`, `discount_config`, `cost`, `recharge`) VALUES (3, '腰缠万贯', '/assets/static/images/group/ic_user level_3.png', null, 0.20, 100.00);

INSERT INTO `__PREFIX__user_group` (`id`, `name`, `icon`, `discount_config`, `cost`, `recharge`) VALUES (4, '富甲一方', '/assets/static/images/group/ic_user level_4.png', null, 0.15, 200.00);

INSERT INTO `__PREFIX__user_group` (`id`, `name`, `icon`, `discount_config`, `cost`, `recharge`) VALUES (5, '富可敌国', '/assets/static/images/group/ic_user level_5.png', null, 0.10, 300.00);

INSERT INTO `__PREFIX__user_group` (`id`, `name`, `icon`, `discount_config`, `cost`, `recharge`) VALUES (6, '至尊', '/assets/static/images/group/ic_user level_6.png', null, 0.05, 500.00);

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('lang_registry', '[{"code":"zh-cn","enabled":true},{"code":"zh-tw","enabled":true},{"code":"en","enabled":true},{"code":"ru","enabled":true},{"code":"vi","enabled":true},{"code":"ja","enabled":false}]');

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('contact_widget_email', '');

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('payment_method_alipay', '0');

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('payment_method_binding_alipay', '0');

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('payment_method_wxpay', '0');

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('payment_method_binding_wxpay', '0');

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('payment_method_usdt', '0');

INSERT INTO `__PREFIX__config` (`key`, `value`) VALUES ('payment_method_binding_usdt', '0');

SET FOREIGN_KEY_CHECKS = 1;
